// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckNucleiInstalled() {
  return window['go']['main']['App']['CheckNucleiInstalled']();
}

export function ClearAllTemplates() {
  return window['go']['main']['App']['ClearAllTemplates']();
}

export function ConfirmAndImportTemplates(arg1) {
  return window['go']['main']['App']['ConfirmAndImportTemplates'](arg1);
}

export function CreateScanTask(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateScanTask'](arg1, arg2, arg3);
}

export function DeleteScanResult(arg1) {
  return window['go']['main']['App']['DeleteScanResult'](arg1);
}

export function DeleteScanTask(arg1) {
  return window['go']['main']['App']['DeleteScanTask'](arg1);
}

export function DeleteTemplate(arg1) {
  return window['go']['main']['App']['DeleteTemplate'](arg1);
}

export function ExportTaskResultAsJSON(arg1) {
  return window['go']['main']['App']['ExportTaskResultAsJSON'](arg1);
}

export function GetAllScanResults() {
  return window['go']['main']['App']['GetAllScanResults']();
}

export function GetAllScanTasks() {
  return window['go']['main']['App']['GetAllScanTasks']();
}

export function GetAllTemplates() {
  return window['go']['main']['App']['GetAllTemplates']();
}

export function GetAppInfo() {
  return window['go']['main']['App']['GetAppInfo']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetPOCTemplateContent(arg1) {
  return window['go']['main']['App']['GetPOCTemplateContent'](arg1);
}

export function GetRunningScanTasks() {
  return window['go']['main']['App']['GetRunningScanTasks']();
}

export function GetScanResult(arg1) {
  return window['go']['main']['App']['GetScanResult'](arg1);
}

export function GetScanResults(arg1) {
  return window['go']['main']['App']['GetScanResults'](arg1);
}

export function GetScanTaskResult(arg1) {
  return window['go']['main']['App']['GetScanTaskResult'](arg1);
}

export function GetTaskHTTPLogs(arg1) {
  return window['go']['main']['App']['GetTaskHTTPLogs'](arg1);
}

export function GetTaskLogSummary(arg1) {
  return window['go']['main']['App']['GetTaskLogSummary'](arg1);
}

export function GetTaskLogs(arg1) {
  return window['go']['main']['App']['GetTaskLogs'](arg1);
}

export function GetTaskLogsFromFile(arg1) {
  return window['go']['main']['App']['GetTaskLogsFromFile'](arg1);
}

export function GetTaskProgress(arg1) {
  return window['go']['main']['App']['GetTaskProgress'](arg1);
}

export function ImportTemplates(arg1) {
  return window['go']['main']['App']['ImportTemplates'](arg1);
}

export function ListResultFiles() {
  return window['go']['main']['App']['ListResultFiles']();
}

export function PauseScanTask(arg1) {
  return window['go']['main']['App']['PauseScanTask'](arg1);
}

export function PreValidateTemplates(arg1) {
  return window['go']['main']['App']['PreValidateTemplates'](arg1);
}

export function ReloadConfig() {
  return window['go']['main']['App']['ReloadConfig']();
}

export function RescanTask(arg1) {
  return window['go']['main']['App']['RescanTask'](arg1);
}

export function SaveCSVFile(arg1, arg2) {
  return window['go']['main']['App']['SaveCSVFile'](arg1, arg2);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SavePOCTemplate(arg1, arg2) {
  return window['go']['main']['App']['SavePOCTemplate'](arg1, arg2);
}

export function SearchTemplates(arg1, arg2) {
  return window['go']['main']['App']['SearchTemplates'](arg1, arg2);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SelectNucleiDirectory() {
  return window['go']['main']['App']['SelectNucleiDirectory']();
}

export function SetNucleiPath(arg1) {
  return window['go']['main']['App']['SetNucleiPath'](arg1);
}

export function StartScanTask(arg1) {
  return window['go']['main']['App']['StartScanTask'](arg1);
}

export function StopScanTask(arg1) {
  return window['go']['main']['App']['StopScanTask'](arg1);
}

export function TestNucleiPath(arg1) {
  return window['go']['main']['App']['TestNucleiPath'](arg1);
}

export function TestProxies(arg1) {
  return window['go']['main']['App']['TestProxies'](arg1);
}

export function TestSinglePOC(arg1) {
  return window['go']['main']['App']['TestSinglePOC'](arg1);
}

export function UpdateScanTask(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateScanTask'](arg1, arg2, arg3, arg4);
}

export function ValidateNucleiPath() {
  return window['go']['main']['App']['ValidateNucleiPath']();
}
