// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {scanner} from '../models';
import {main} from '../models';

export function CheckNucleiInstalled():Promise<boolean>;

export function ClearAllTemplates():Promise<void>;

export function ConfirmAndImportTemplates(arg1:Array<models.Template>):Promise<scanner.ImportResult>;

export function CreateScanTask(arg1:string,arg2:string,arg3:string):Promise<scanner.TaskConfig>;

export function DeleteScanResult(arg1:string):Promise<void>;

export function DeleteScanTask(arg1:number):Promise<void>;

export function DeleteTemplate(arg1:string):Promise<void>;

export function GetAllScanResults():Promise<Array<scanner.TaskResult>>;

export function GetAllScanTasks():Promise<Array<scanner.TaskConfig>>;

export function GetAllTemplates():Promise<Array<models.Template>>;

export function GetAppInfo():Promise<Record<string, string>>;

export function GetConfig():Promise<models.Config>;

export function GetRunningScanTasks():Promise<Array<models.ScanTask>>;

export function GetScanResult(arg1:number):Promise<Record<string, any>>;

export function GetScanResults(arg1:number):Promise<Array<models.NucleiResult>>;

export function GetScanTaskResult(arg1:number):Promise<scanner.TaskResult>;

export function GetTaskLogSummary(arg1:number):Promise<Record<string, any>>;

export function GetTaskLogs(arg1:number):Promise<Array<models.ScanLog>>;

export function GetTaskLogsFromFile(arg1:number):Promise<Array<scanner.ScanLogEntry>>;

export function GetTaskProgress(arg1:number):Promise<models.TaskProgress>;

export function ImportTemplates(arg1:string):Promise<scanner.ImportResult>;

export function ListResultFiles():Promise<Array<Record<string, any>>>;

export function PauseScanTask(arg1:number):Promise<void>;

export function PreValidateTemplates(arg1:string):Promise<scanner.ImportResult>;

export function ReloadConfig():Promise<void>;

export function RescanTask(arg1:number):Promise<void>;

export function SaveConfig(arg1:models.Config):Promise<void>;

export function SearchTemplates(arg1:string,arg2:string):Promise<Array<models.Template>>;

export function SelectDirectory():Promise<string>;

export function SelectNucleiDirectory():Promise<string>;

export function SetNucleiPath(arg1:string):Promise<void>;

export function StartScanTask(arg1:number):Promise<void>;

export function StopScanTask(arg1:number):Promise<void>;

export function TestNucleiPath(arg1:string):Promise<main.NucleiTestResult>;

export function ValidateNucleiPath():Promise<void>;
